OneginSortv2/main.c
NAME
OneginSortv2/main.c - Created by Александр Дремов on 28.08.2020.
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <ctype.h>
#include <assert.h>
#include <locale.h>
Data Structures
struct SortedLinesContainer
struct string
Used to store char* and its len so that computations are more effective.
Typedefs
typedef struct SortedLinesContainer SortedLinesContainer
typedef struct string string
Used to store char* and its len so that computations are more effective.
Functions
void adjustLenTrimming (string *line)
Decreases line length so that to ignore trailing whitespaces and punctuation.
int allocateContainer (struct SortedLinesContainer *this)
Check SortedLinesContainer allocate for information.
int compar (const void *, const void *)
Check SortedLinesContainer compar for information.
int comparRev (const void *, const void *)
Check SortedLinesContainer comparRev for information.
int construct (struct SortedLinesContainer *this, const char *fullBuffer, const size_t length, const bool fromEnd)
Check SortedLinesContainer construct for information.
int constructFromFile (struct SortedLinesContainer *this, const char *fileName, const bool fromEnd)
Constructs SortedLinesContainer from file.
void defaultContainer (struct SortedLinesContainer *this)
Sets default values for SortedLinesContainer.
void doubleWhitespacesSkip (const string *line, const char *lineCurrent, short *lineSleep, const int modifier)
Set lineSleep to 1 if current position is somewhere between reacurring whitespaces.
void freeContainer (struct SortedLinesContainer *this)
Check SortedLinesContainer free for information.
bool hasVisibleContent (const string line)
Checks whether string consists only of invisible characters.
bool isprintable (char c)
Is char is visible.
bool ispunctuation (char c)
Is char is punctuation.
void lineAnalyze (const char *lineCurrent, short *insideLine, short *lineSleep)
Line analyzer.
int main (int argc, const char *argv[])
int multiCompare (const void *line1, const void *line2, const int fromEnd)
Compare strings lexicographically, removing punctuation, trimming unprintable, and removing double whitespaces.
size_t outputContainer (SortedLinesContainer *this, FILE *fp)
Outputs container line-by-line to the file.
size_t outputContainerUnsorted (SortedLinesContainer *this, FILE *fp)
Outputs container line-by-line to the file without sorting.
int parseArgs (const int argc, const char *argv[], bool *reversed, bool *runTests, bool *dedTask, char **inputFileName, char **outputFileName)
Parses arguments from command line.
bool performAllTests (void)
Performs all tests and returns true if valid.
void sortContainer (struct SortedLinesContainer *this)
Check SortedLinesContainer sort for information.
size_t taskOutput (SortedLinesContainer *container, FILE *fp, const bool dedTask)
Outputs resulted container to the file, checking for Dedinsky mode.
bool testContainer (void)
Tests for SortedLinesContainer.
bool tests_hasVisibleContent (void)
Tests for hasVisibleContent().
int tests_multiCompare (void)
Tests for doubleWhitespacesSkip()
Detailed Description
Created by Александр Дремов on 28.08.2020.
Available command line params:
Parameters
-r sort from the end
&ndash;input <filepath> input file
&ndash;output <filepath> output file
&ndash;test run tests before executing
&ndash;dedtask output in Dedinsky's task format (Dedinsky mode)
Copyright
Copyright © 2020 alexdremov. All rights reserved.
Definition in file main.c.
Typedef Documentation
typedef struct SortedLinesContainer SortedLinesContainer
typedef struct string string
Used to store char* and its len so that computations are more effective.
Function Documentation
void adjustLenTrimming (string * line)
Decreases line length so that to ignore trailing whitespaces and punctuation.
Parameters
line [in + out] full analyzed string
Definition at line 984 of file main.c.
                                     {
    char *pos = line->contents + line->len;
    if (line->len == 0)
        return;
    pos--;
    while (pos != line->contents) {
        if (isprintable(*pos) && !ispunctuation(*pos))
            break;
        pos--;
        line->len--;
    }
}
References string::contents, isprintable(), ispunctuation(), and string::len.
Referenced by multiCompare().
int allocateContainer (struct SortedLinesContainer * this)
Check SortedLinesContainer allocate for information.
Definition at line 706 of file main.c.
                                                         {
    assert(this != NULL);
    
    if (!this->lines || this->linesMaxNumber == 0) {
        this->lines = calloc(this->allocIncrement, sizeof(string));
        
        if (this->lines == NULL) {
            printf("Failed allocating memory in allocateContainer()\n");
            this->free(this);
            return EXIT_FAILURE;
        }
        this->linesMaxNumber = this->allocIncrement;
    } else {
        if (this->linesNumber + 1 >= this->linesMaxNumber) {
            this->linesMaxNumber += this->allocIncrement;
            string *newAllocation = realloc(this->lines, this->linesMaxNumber * sizeof(string));
            
            if (newAllocation == NULL) {
                printf("Failed reallocating memory in allocateContainer()\n");
                this->free(this);
                return EXIT_FAILURE;
            } else {
                this->lines = newAllocation;
            }
            
        }
    }
    return EXIT_SUCCESS;
}
References SortedLinesContainer::allocIncrement, SortedLinesContainer::free, SortedLinesContainer::lines, SortedLinesContainer::linesMaxNumber, and SortedLinesContainer::linesNumber.
Referenced by defaultContainer().
int compar (const void * line1, const void * line2)
Check SortedLinesContainer compar for information.
Definition at line 737 of file main.c.
                                                 {
    assert(line1 != NULL);
    assert(line2 != NULL);
    assert(line1 != line2);
    
    return multiCompare(line1, line2, 0);
}
References multiCompare().
Referenced by defaultContainer(), and sortContainer().
int comparRev (const void * line1, const void * line2)
Check SortedLinesContainer comparRev for information.
Definition at line 746 of file main.c.
                                                    {
    assert(line1 != NULL);
    assert(line2 != NULL);
    assert(line1 != line2);
    
    return multiCompare(line1, line2, 1);
}
References multiCompare().
Referenced by defaultContainer(), and sortContainer().
int construct (struct SortedLinesContainer * this, const char * fullBuffer, const size_t length, const bool fromEnd)
Check SortedLinesContainer construct for information.
Definition at line 516 of file main.c.
                                                       {
    assert(this != NULL);
    assert(fullBuffer != NULL);
    
    this->fullBuffer = calloc(length + 1, sizeof(char));
    this->fullBufferInitial = calloc(length + 1, sizeof(char));
    if (!this->fullBuffer) {
        printf("Can't allocate space for fullBuffer in construct()\n");
        this->free(this);
        return EXIT_FAILURE;
    }
    
    this->fromEnd = fromEnd;
    
    size_t curCounter = 0;
    for (size_t i = 0; i < length; i++) {
        this->fullBuffer[i] =
        this->fullBufferInitial[i] = fullBuffer[i];
        if (curCounter == 0) {
            this->allocate(this);
            string newLocated = {(this->fullBuffer + i), 0, false};
            this->lines[this->linesNumber] = newLocated;
            this->linesNumber += 1;
            curCounter++;
            continue;
        }
        if (this->fullBuffer[i] == '\n' || this->fullBuffer[i] == '\0') {
            this->fullBuffer[i] = '\0';
            (this->lines + this->linesNumber - 1)->len = curCounter;
            curCounter = 0;
            continue;
        }
        curCounter++;
    }
    if (curCounter != 0) {
        (this->lines + this->linesNumber - 1)->len = curCounter;
    }
    this->fullBuffer[length] = '\0';
    return EXIT_SUCCESS;
}
References SortedLinesContainer::allocate, SortedLinesContainer::free, SortedLinesContainer::fromEnd, SortedLinesContainer::fullBuffer, SortedLinesContainer::fullBufferInitial, SortedLinesContainer::lines, and SortedLinesContainer::linesNumber.
Referenced by constructFromFile(), main(), and testContainer().
int constructFromFile (struct SortedLinesContainer * this, const char * fileName, const bool fromEnd)
Constructs SortedLinesContainer from file.
Definition at line 565 of file main.c.
                                                                                                   {
    char *buffer = 0;
    size_t length = 0;
    FILE *fp = fopen(fileName, "rb");
    
    if (fp) {
        fseek(fp, 0, SEEK_END);
        length = (size_t) ftell(fp);
        fseek(fp, 0, SEEK_SET);
        buffer = calloc(length, sizeof(char));
        if (buffer) {
            fread(buffer, 1, length, fp);
        } else {
            printf("Can't allocate memory "
                   "for buffer in constructFromFile()\n");
            free(buffer);
            this->free(this);
            return EXIT_FAILURE;
        }
        fclose(fp);
        size_t lenElements = length / sizeof(char);
        size_t newLinesNum = 0;
        for (size_t i = 0; i < lenElements; i++){
            if (buffer[i] == '\n'){
                newLinesNum++;
            }
        }
        defaultContainer(this);
        
        this->lines = calloc(newLinesNum + 1, sizeof(string));
        this->linesMaxNumber = newLinesNum + 1;
        
        int constructResult = this->construct(this, buffer, lenElements, fromEnd);
        if (constructResult == EXIT_FAILURE) {
            printf("Failed constructing object in constructFromFile()\n");
            free(buffer);
            return EXIT_FAILURE;
        }
        this->sort(this);
        free(buffer);
    } else {
        printf("Can't open %s for read\n", fileName);
        return EXIT_FAILURE;
    }
    return EXIT_SUCCESS;
}
References construct(), defaultContainer(), SortedLinesContainer::free, SortedLinesContainer::fromEnd, SortedLinesContainer::lines, SortedLinesContainer::linesMaxNumber, and SortedLinesContainer::sort.
Referenced by main().
void defaultContainer (struct SortedLinesContainer * this)
Sets default values for SortedLinesContainer.
Definition at line 1015 of file main.c.
                                                         {
    this->allocIncrement = 1024;
    this->linesNumber = 0;
    this->fromEnd = false;
    this->linesMaxNumber = 0;
    this->allocate = &allocateContainer;
    this->compar = &compar;
    this->comparRev = &comparRev;
    this->sort = &sortContainer;
    this->free = &freeContainer;
    this->fullBuffer = NULL;
    this->fullBufferInitial = NULL;
    this->lines = NULL;
}
References allocateContainer(), compar(), comparRev(), freeContainer(), and sortContainer().
Referenced by constructFromFile(), and testContainer().
void doubleWhitespacesSkip (const string * line, const char * lineCurrent, short * lineSleep, const int modifier)
Set lineSleep to 1 if current position is somewhere between reacurring whitespaces.
Parameters
line [in] line to be checked
lineCurrent [in] current position
lineSleep [out] skip this symbol?
modifier [in] 1 or -1 - direction of scaning (forwards or backwards)
Definition at line 969 of file main.c.
                                                                                                              {
    if (modifier > 0) {
        if (lineCurrent >= (line->contents + 1)) {
            if (*lineCurrent == ' ' && *(lineCurrent - 1) == ' ')
                *lineSleep = 1;
        }
    } else {
        if (lineCurrent <= (line->contents + line->len - 1)) {
            if (*lineCurrent == ' ' && *(lineCurrent + 1) == ' ')
                *lineSleep = 1;
        }
    }
}
References string::contents, and string::len.
Referenced by multiCompare().
void freeContainer (struct SortedLinesContainer * this)
Check SortedLinesContainer free for information.
Definition at line 681 of file main.c.
                                                      {
    for (size_t i = 0; i < this->linesNumber; i++) {
        if (this->lines[i].allocated)
            free(this->lines[i].contents);
    }
    if (this->lines)
        free(this->lines);
    
    if (this->fullBuffer)
        free(this->fullBuffer);
    
    if (this->fullBufferInitial)
        free(this->fullBufferInitial);
}
References SortedLinesContainer::free, SortedLinesContainer::fullBuffer, SortedLinesContainer::fullBufferInitial, SortedLinesContainer::lines, and SortedLinesContainer::linesNumber.
Referenced by defaultContainer().
bool hasVisibleContent (const string line)
Checks whether string consists only of invisible characters.
Parameters
line [in] string to check
Returns
if has some visible content
Definition at line 470 of file main.c.
                                          {
    for (size_t i = 0; i < line.len; i++){
        if (isprintable(line.contents[i])){
            return true;
        }
    }
    return false;
}
References string::contents, isprintable(), and string::len.
Referenced by outputContainer(), and tests_hasVisibleContent().
bool isprintable (char c)
Is char is visible.
Parameters
c [in] char to be checked
Definition at line 1031 of file main.c.
                         {
    return !(c == '\n' || c == '\t' || c == ' ' || c == '\r' || c == '\0');
}
Referenced by adjustLenTrimming(), hasVisibleContent(), and lineAnalyze().
bool ispunctuation (char c)
Is char is punctuation.
Parameters
c [in] char to be checked
Definition at line 1036 of file main.c.
                           {
    return ispunct(c) || c > 'z';
}
Referenced by adjustLenTrimming(), and lineAnalyze().
void lineAnalyze (const char * lineCurrent, short * insideLine, short * lineSleep)
Line analyzer. Fires sleep if current symbol is not ready to be compared with something (skip this symbol)
Parameters
lineCurrent [in] line current position
insideLine [in + out] whether inside line (leading whitespaces skipped)
lineSleep [in + out] whether to skip current symbol
Definition at line 998 of file main.c.
                                                                               {
    if (!isprintable(*lineCurrent) && !*insideLine) {
        *lineSleep = 1;
        return;
    }
    if (isprintable(*lineCurrent) && !*insideLine) {
        *insideLine = 1;
        *lineSleep = 0;
    }
    if (ispunctuation(*lineCurrent)) {
        *lineSleep = 1;
    } else {
        *lineSleep = 0;
    }
}
References isprintable(), and ispunctuation().
Referenced by multiCompare().
int main (int argc, const char * argv[])
Definition at line 297 of file main.c.
                                       {
    setlocale(LC_ALL, "Russian");
    setlocale(LC_NUMERIC, "English");
    
    bool reversed = false;
    bool runTests = false;
    bool dedTask = false;
    
    char *inputFileName = calloc(10, sizeof(char));
    char *outputFileName = calloc(11, sizeof(char));
    
    if (inputFileName == NULL || outputFileName == NULL){
        printf("Failed allocating memory\n");
        if (inputFileName != NULL)
            free(inputFileName);
        if (outputFileName != NULL)
            free(outputFileName);
        return EXIT_FAILURE;
    }
    strcpy(inputFileName, "input.txt"); // argv pointer
    strcpy(outputFileName, "output.txt");
    
    if (parseArgs(argc, argv, &reversed, &runTests,
                  &dedTask, &inputFileName, &outputFileName) == EXIT_FAILURE){
        return EXIT_FAILURE;
    }
    
    printf("Aleksandr Dremov\n"
           "(c) 2020 all rights reserved\n\n");
    if (runTests) {
        if (performAllTests()) {
            printf("All tests passed\n");
        } else {
            printf("Some tests failed!\n");
            free(inputFileName);
            free(outputFileName);
            return EXIT_FAILURE;
        }
    }
    
    printf("Will sort %s file and output to %s\n", inputFileName, outputFileName);
    if (!dedTask)
        printf("Is sort from the end: %s\n", (reversed) ? "true" : "false");
    
    SortedLinesContainer container = { &construct };
    
    int constructResult = constructFromFile(&container, inputFileName, reversed);
    if (constructResult == EXIT_FAILURE) {
        printf("Failed constructFromFile()\n");
        free(inputFileName);
        free(outputFileName);
        container.free(&container);
        return EXIT_FAILURE;
    }
    
    FILE *fp = fopen(outputFileName, "w");
    if (fp == NULL){
        printf("Cant open %s for output\n", outputFileName);
        free(inputFileName);
        free(outputFileName);
        container.free(&container);
        return EXIT_FAILURE;
    }
    size_t linesWrote = taskOutput(&container, fp, dedTask);
    
    fclose(fp);
    free(inputFileName);
    free(outputFileName);
    container.free(&container);
    return (linesWrote == 0)? EXIT_FAILURE : EXIT_SUCCESS;
}
References construct(), constructFromFile(), SortedLinesContainer::free, parseArgs(), performAllTests(), and taskOutput().
int multiCompare (const void * line1, const void * line2, const int fromEnd)
Compare strings lexicographically, removing punctuation, trimming unprintable, and removing double whitespaces.
Parameters
line1 [in] first line
line2 [in] second line
fromEnd [in] whether to compare from the end
Definition at line 754 of file main.c.
                                                                          {
    string *line1String = (struct string *) line1;
    string *line2String = (struct string *) line2;
    
    // Strings are not copied. Just a reference with different length
    string tmpString1 = {line1String->contents, line1String->len, line1String->allocated};
    string tmpString2 = {line2String->contents, line2String->len, line2String->allocated};
    
    adjustLenTrimming(&tmpString1);
    adjustLenTrimming(&tmpString2);
    
    char *line1Current = line1String->contents;
    char *line2Current = line2String->contents;
    
    short insideLine1 = 0, insideLine2 = 0;
    short line1Ended = 0, line2Ended = 0;
    short line1Sleep = 1, line2Sleep = 1;
    
    short line1Cyr = 1, line2Cyr = 1;
    
    short int modifier = 1;
    if (fromEnd) {
        modifier = -1;
        line1Current += tmpString1.len;
        if (tmpString1.len != 0)
            line1Current -= 1;
        
        line2Current += tmpString2.len;
        if (tmpString2.len != 0)
            line2Current -= 1;
    }
    
    while (1) {
        if (line1Current < tmpString1.contents){
            line1Ended = 1;
            line1Sleep = 1;
        } else if (*line1Current == '\0' || line1Ended || line1Current >= tmpString1.contents + tmpString1.len) {
            line1Ended = 1;
            line1Sleep = 1;
        } else {
            lineAnalyze(line1Current, &insideLine1, &line1Sleep);
            doubleWhitespacesSkip(&tmpString1, line1Current, &line1Sleep, modifier);
        }
        
        if (line2Current < tmpString2.contents){
            line2Ended = 1;
            line2Sleep = 1;
        } else if (*line2Current == '\0' || line2Ended || line2Current >= tmpString2.contents + tmpString2.len) {
            line2Ended = 1;
            line2Sleep = 1;
        } else {
            lineAnalyze(line2Current, &insideLine2, &line2Sleep);
            doubleWhitespacesSkip(&tmpString2, line2Current, &line2Sleep, modifier);
        }
        
        // define
        
        line1Cyr = 0;
        line2Cyr = 0;
        if (modifier == -1){
            if (line1Current > tmpString1.contents && line1Sleep == 0){
                if (*(line1Current - 1) == -47 || *(line1Current - 1) == -48){
                    line1Cyr = 1;
                }
            }
            
            if (line2Current > tmpString2.contents && line2Sleep == 0){
                if (*(line2Current - 1) == -47 || *(line2Current - 1) == -48){
                    line2Cyr = 1;
                }
            }
            
            if (line1Cyr == 1 && line2Cyr == 1){
                // Two bytes of first cyr letter
                int a1 = *(line1Current - 1);
                int a2 = *line1Current;
                
                // Two bytes of second cyr letter
                int b1 = *(line2Current - 1);
                int b2 = *(line2Current);
                int retVal = a2 + 1000 * a1 - (b2 + 1000 * b1);
                if (retVal == 0){
                    line1Current += modifier * 2;
                    line2Current += modifier * 2;
                    continue;
                }
                return retVal;
            } else if (line1Cyr == 1 && line2Cyr == 0){
                return -1;
            } else if (line1Cyr == 0 && line2Cyr == 1){
                return 1;
            }
        }
        
        if (line1Ended == 1 || line2Ended == 1)
            break;
        
        if (line1Sleep == 1 && line2Sleep == 0) {
            line1Current += modifier;
        } else if (line1Sleep == 0 && line2Sleep == 1) {
            line2Current += modifier;
        } else if (line1Sleep == 1 && line2Sleep == 1) {
            line1Current += modifier;
            line2Current += modifier;
        } else {
            if (*line1Current == *line2Current) {
                line1Current += modifier;
                line2Current += modifier;
                continue;
            }
            return *line1Current - *line2Current;
        }
        if (modifier == -1 && line1Current == line1String->contents) {
            line1Ended = 1;
            line1Sleep = 1;
        }
        if (modifier == -1 && line2Current == line2String->contents) {
            line1Ended = 1;
            line1Sleep = 1;
        }
    }
    if (line1Ended == line2Ended)
        return 0;
    else {
        return line1Ended - line2Ended;
    }
}
References adjustLenTrimming(), string::allocated, string::contents, doubleWhitespacesSkip(), string::len, and lineAnalyze().
Referenced by compar(), comparRev(), and tests_multiCompare().
size_t outputContainer (SortedLinesContainer * this, FILE * fp)
Outputs container line-by-line to the file.
Parameters
this [in] container
fp [in] file pointer
Returns
number of lines written
Definition at line 1041 of file main.c.
                                                             {
    assert(this != NULL);
    if (fp == NULL) {
        printf("Could not open file for output\n");
        return 0;
    }
    
    for (size_t i = 0; i < this->linesNumber; i++) {
        if (!hasVisibleContent(*(this->lines + i)))
            continue;
        fputs((this->lines + i)->contents, fp);
        fputs("\n", fp);
    }
    
    return this->linesNumber;
}
References string::contents, and hasVisibleContent().
Referenced by taskOutput().
size_t outputContainerUnsorted (SortedLinesContainer * this, FILE * fp)
Outputs container line-by-line to the file without sorting.
Parameters
this [in] container
fp [in] file pointer
Returns
0 - success, 1 - error
Definition at line 1058 of file main.c.
                                                                     {
    assert(this != NULL);
    if (fp == NULL) {
        printf("Could not open file for output\n");
        return 1;
    }
    fprintf(fp, "%s", this->fullBufferInitial);
    
    return 0;
}
Referenced by taskOutput().
int parseArgs (const int argc, const char * argv[], bool * reversed, bool * runTests, bool * dedTask, char ** inputFileName, char ** outputFileName)
Parses arguments from command line.
Parameters
argc [in] arguments count
argv [in] arguments strings
reversed [out] sort from end or not
runTests [out] run unit tests or not
dedTask [out] Dedinsky mode flag
inputFileName [out] input file name
outputFileName [out] outputfile name
Definition at line 400 of file main.c.
                                                                          {
    for (int i = 0; i < argc; i++) {
        if (strcmp("-r", argv[i]) == 0) {
            *reversed = true;
            continue;
        }
        
        if (strcmp("--dedtask", argv[i]) == 0) {
            *dedTask = true;
            continue;
        }
        
        if (strcmp("--test", argv[i]) == 0) {
            *runTests = true;
            continue;
        }
        
        if (strcmp("--output", argv[i]) == 0) {
            i++;
            if (i >= argc){
                printf("Not found output file name.\n"
                       "Please, provide filename after --output flag\n");
                return EXIT_FAILURE;
            }
            size_t len = strlen(argv[i]);
            char *outputFileNameNew = realloc(*outputFileName, sizeof(char) * (len + 1));
            if (outputFileNameNew == NULL) {
                printf("Can't realloc memory for output file name\n");
                return EXIT_FAILURE;
            } else {
                *outputFileName = outputFileNameNew;
            }
            strcpy(*outputFileName, argv[i]);
            continue;
        }
        if (strcmp("--input", argv[i]) == 0) {
            i++;
            if (i >= argc){
                printf("Not found input file name.\n"
                       "Please, provide filename after --input flag\n");
                return EXIT_FAILURE;
            }
            size_t len = strlen(argv[i]);
            
            char *inputFileNameNew = realloc(*inputFileName, sizeof(char) * (len + 1));
            if (inputFileNameNew == NULL) {
                printf("Can't realloc memory for input file name\n");
                return EXIT_FAILURE;
            } else {
                *inputFileName = inputFileNameNew;
            }
            
            strcpy(*inputFileName, argv[i]);
            continue;
        }
    }
    return EXIT_SUCCESS;
}
Referenced by main().
bool performAllTests (void)
Performs all tests and returns true if valid.
Returns
success
Definition at line 463 of file main.c.
                       {
    return tests_multiCompare() &&
           tests_hasVisibleContent() &&
           testContainer();
}
References testContainer(), tests_hasVisibleContent(), and tests_multiCompare().
Referenced by main().
void sortContainer (struct SortedLinesContainer * this)
Check SortedLinesContainer sort for information.
Definition at line 697 of file main.c.
                                                      {
    if (!this->fromEnd) {
        qsort(this->lines, this->linesNumber, sizeof(string), this->compar);
    } else {
        qsort(this->lines, this->linesNumber, sizeof(string), this->comparRev);
    }
}
References compar(), comparRev(), SortedLinesContainer::fromEnd, SortedLinesContainer::lines, and SortedLinesContainer::linesNumber.
Referenced by defaultContainer().
size_t taskOutput (SortedLinesContainer * container, FILE * fp, const bool dedTask)
Outputs resulted container to the file, checking for Dedinsky mode.
Parameters
container [in], in Dedinsky mode: [in+out] container to be used
fp [in] file pointer
dedTask [in] whether Dedinsky mode was specified
Definition at line 371 of file main.c.
                                                                                {
    size_t linesWrote = 0;
    if (dedTask){
        printf("\nMEOW! You activated Dedinsky mode.\
               \nFasten your seatbelts, please.\n");
        printf("\
         _ ___ _.--.\n\
         \`.|\..----...-'` `-._.-'_.-'`\n\
         / ' ` , __.--'\n\
         )/' _/ \ `-_, /\n\
         `-'\" `\"\_ ,_.-;_.-\_ \\n\
             _.-'_./ {_.' ; /\n\
            {_.---' {_/\n\n");
        fprintf(fp, "=== Unsorted container ===\n");
        outputContainerUnsorted(container, fp);
        container->fromEnd = false;
        fprintf(fp, "\n\n=== Sorted container ===\n");
        linesWrote += outputContainer(container, fp);
        container->fromEnd = true;
        container->sort(container);
        fprintf(fp, "\n\n=== Sorted from the end container ===\n");
        linesWrote += outputContainer(container, fp);
    }else{
        linesWrote = outputContainer(container, fp);
    }
    return linesWrote;
}
References SortedLinesContainer::fromEnd, outputContainer(), outputContainerUnsorted(), and SortedLinesContainer::sort.
Referenced by main().
bool testContainer (void)
Tests for SortedLinesContainer.
Returns
success
Definition at line 613 of file main.c.
                     {
    
    string input[] = {
        {"", 0, false},
        {"b\na\n", 0, false},
        {"b\naa\n", 0, false},
        {"", 0, false},
        {"a", 0, false},
        {"aba\naaa", 0, false},
        {"aca\na-ba", 0, false},
        {"aba\naba\n !aaa", 0, false}
    };
    
    string output[] = {
        {"", 0, false},
        {"a\nb\n", 0, false},
        {"aa\nb\n", 0, false},
        {"", 0, false},
        {"a\n", 0, false},
        {"aaa\naba\n", 0, false},
        {"a-ba\naca\n", 0, false},
        {" !aaa\naba\naba\n", 0, false}
    };
    
    assert(sizeof(output) / sizeof(string) == sizeof(input) / sizeof(string));
    
    bool valid = true;
    
    for (size_t i = 0; i < sizeof(output) / sizeof(string); i++){
        input[i].len = strlen(input[i].contents);
        output[i].len = strlen(output[i].contents);
        
        size_t curPos = 0;
        char *tmpStringOutput = calloc(output[i].len * 2 + 1, sizeof(char));
        
        SortedLinesContainer container = {};
        defaultContainer(&container);
        container.construct = &construct;
        container.construct(&container, input[i].contents, input[i].len, true);
        
        container.sort(&container);
        
        for (size_t j = 0; j < container.linesNumber; j++){
            strcpy(tmpStringOutput + curPos, container.lines[j].contents);
            tmpStringOutput[curPos + container.lines[j].len] = '\n';
            curPos += container.lines[j].len + 1;
        }
        tmpStringOutput[curPos] = '\0';
        if (strcmp(tmpStringOutput, output[i].contents) != 0){
            printf("Integration test #(%lu) failure\n"
                   "Expected:\n|||\n", i + 1);
            printf("%s\n", output[i].contents);
            printf("|||\n");
            printf("Received:\n"
                   "|||\n");
            printf("%s\n", tmpStringOutput);
            printf("|||\n");
            valid = false;
        }
        
        container.free(&container);
        
        free(tmpStringOutput);
    }
    return valid;
}
References construct(), SortedLinesContainer::construct, string::contents, defaultContainer(), SortedLinesContainer::free, string::len, SortedLinesContainer::lines, SortedLinesContainer::linesNumber, and SortedLinesContainer::sort.
Referenced by performAllTests().
bool tests_hasVisibleContent (void)
Tests for hasVisibleContent().
Returns
if valid
Definition at line 480 of file main.c.
                              {
    string inputs[] = {
        {" ", 1, false},
        {"", 0, false},
        {"asd", 3, false},
        {"a", 1, false},
        {"\n", 1, false},
        {"\0", 1, false}
    };
    
    bool outputs[] = {
        false,
        false,
        true,
        true,
        false,
        false
    };
    
    assert(sizeof(outputs)/sizeof(bool) == sizeof(inputs)/sizeof(string));
    
    int totalNumber = sizeof(outputs)/sizeof(bool);
    bool valid = true;
    
    for (int i = 0; i<totalNumber; i++) {
        bool actualOutput = hasVisibleContent(inputs[i]);
        if (!(actualOutput == outputs[i])) {
            printf("Failed hasVisibleContent test #(%d) %d!=%d\n", i+1, actualOutput, outputs[i]);
            valid = false;
        }
    }
    
    return valid;
}
References hasVisibleContent().
Referenced by performAllTests().
int tests_multiCompare (void)
Tests for doubleWhitespacesSkip()
Definition at line 883 of file main.c.
                             {
    string inputs1[] = {
        {"", 0, false},
        {" ", 0, false},
        {" a", 0, false},
        {" a ", 0, false},
        {"b", 0, false},
        {"\"b", 0, false},
        {"a-ba", 0, false},
        {"a b a", 0, false},
        {"a", 0, false},
        {"а", 0, false},
        {"а-", 0, false},
        {"а-а-", 0, false},
        {"ба", 0, false},
    };
    string inputs2[] = {
        {"", 0, false},
        {" ", 0, false},
        {"a", 0, false},
        {"a", 0, false},
        {"a", 0, false},
        {"b", 0, false},
        {"aba", 0, false},
        {"a b a", 0, false},
        {"z", 0, false},
        {"я", 0, false},
        {"а", 0, false},
        {"а-а-", 0, false},
        {"аб", 0, false},
    };
    
    bool fromEnd[] = {
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
    };
    
    int outputs[] = {
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        -1,
        -1,
        0,
        0,
        -1
    };
    
    assert(sizeof(outputs) / sizeof(int) == sizeof(inputs1) / sizeof(string) &&
           sizeof(inputs1) / sizeof(string) == sizeof(inputs2) / sizeof(string) &&
           sizeof(fromEnd) / sizeof(bool) == sizeof(inputs2) / sizeof(string));
    
    int totalNumber = sizeof(outputs) / sizeof(int);
    bool valid = true;
    
    for (int i = 0; i < totalNumber; i++) {
        inputs1[i].len = strlen(inputs1[i].contents);
        inputs2[i].len = strlen(inputs2[i].contents);
        int actualOutput = multiCompare(&inputs1[i], &inputs2[i], fromEnd[i]);
        if (!((actualOutput == outputs[i] && outputs[i] == 0) || (outputs[i] > 0 && actualOutput > 0) ||
              (outputs[i] < 0 && actualOutput < 0))) {
            printf("Failed tests_multiCompare test #(%d) %d !~ %d\n", i + 1, actualOutput, outputs[i]);
            valid = false;
        }
    }
    
    return valid;
}
References string::contents, string::len, and multiCompare().
Referenced by performAllTests().
Author
Generated automatically by Doxygen for OneginSortv2 from the source code.