.TH "StackOnSteroids/main.cpp" 3 "Mon Oct 5 2020" "StackRigid" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StackOnSteroids/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'StackRigid\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBStackElementDump\fP(FILE,  VALUE)   {fprintf(FILE, '%g', VALUE);}"
.br
.ti -1c
.RI "#define \fBStackElementType\fP   int"
.br
.RI "Element type to be used in Stack\&. "
.ti -1c
.RI "#define \fBStackElementType\fP   double"
.br
.RI "Element type to be used in Stack\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, const char *argv[])"
.br
.RI "Here, I try somehow to break the Stack\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define StackElementDump(FILE, VALUE)   {fprintf(FILE, '%g', VALUE);}"

.SS "#define StackElementType   int"

.PP
Element type to be used in Stack\&. 
.SS "#define StackElementType   double"

.PP
Element type to be used in Stack\&. 
.SH "Function Documentation"
.PP 
.SS "int main (int argc, const char * argv[])"

.PP
Here, I try somehow to break the Stack\&. 
.PP
.nf
23                                         {
24     StackRigid_int* newStack = NewStackRigid_int(1000, stdout);
25     printf("  size_t volume: %lu bytes\n", sizeof(size_t));
26     printf("checksum volume: %lu bytes\n", sizeof(uint32_t));
27     for(size_t i = 0; i< 1000; i++){
28         StackPush(&newStack, (int)i);
29     }
30     for(size_t i = 0; i < 1000; i++){
31         int tmpVal;
32         StackPop(&newStack, &tmpVal);
33 //        printf("Popped %d\n", tmpVal);
34     }
35     for(size_t i = 0; i < 15; i++){
36         StackPush(&newStack, (int)i + 1);
37     }
38     
39     StackRigid_double* newStackDouble = NewStackRigid_double(1000, stdout);
40     for(size_t i = 0; i< 1000; i++){
41         StackPush(&newStackDouble, (double)(i));
42     }
43     for(size_t i = 0; i < 1000; i++){
44         double tmpVal;
45         StackPop(&newStackDouble, &tmpVal);
46 //        printf("Popped %d\n", tmpVal);
47     }
48     for(size_t i = 0; i < 15; i++){
49         StackPush(&newStackDouble, (double)i + 0\&.5);
50     }
51     
52     size_t memoryUse = StackRigidMemoryUse(newStack);
53     for(size_t i = 0; i < memoryUse; i++){
54         char previousValue = *((char*)newStack + i);
55         for (char bullet = -128; bullet < 127; bullet++){
56             if (bullet == previousValue)
57                 continue;
58             *((char*)newStack + i) = bullet;
59             StackRigidState state = StackValidate(newStack);
60             if (state != STACK_ST_INTEGRITYERR) {
61                 printf("Did not spot intervention at position %zu, byte %x\n", i, bullet);
62                 state = StackValidate(newStack);
63                 StackDump(newStack);
64                 break;
65             }
66         }
67         *((char*)newStack + i) = previousValue;
68     }
69 
70     StackDump(newStack);
71     StackDump(newStackDouble);
72     *((char*)newStackDouble + 10) = 0xFF;
73     StackDump(newStackDouble);
74     StackDestruct(&newStack);
75     return 0;
76 }
.fi
.PP
References STACK_ST_INTEGRITYERR, StackDestruct(), StackDump(), StackPop(), StackPush(), StackRigidMemoryUse(), and StackValidate()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for StackRigid from the source code\&.
