StackOnSteroids/main.cpp
NAME
StackOnSteroids/main.cpp
SYNOPSIS
#include 'StackRigid.h'
Macros
#define StackElementDump(FILE, VALUE) {fprintf(FILE, '%g', VALUE);}
#define StackElementType int
Element type to be used in Stack.
#define StackElementType double
Element type to be used in Stack.
Functions
int main (int argc, const char *argv[])
Here, I try somehow to break the Stack.
Macro Definition Documentation
#define StackElementDump(FILE, VALUE) {fprintf(FILE, '%g', VALUE);}
#define StackElementType int
Element type to be used in Stack.
#define StackElementType double
Element type to be used in Stack.
Function Documentation
int main (int argc, const char * argv[])
Here, I try somehow to break the Stack.
                                        {
    StackRigid_int* newStack = NewStackRigid_int(1000, stdout);
    printf(" size_t volume: %lu bytes\n", sizeof(size_t));
    printf("checksum volume: %lu bytes\n", sizeof(uint32_t));
    for(size_t i = 0; i< 1000; i++){
        StackPush(&newStack, (int)i);
    }
    for(size_t i = 0; i < 1000; i++){
        int tmpVal;
        StackPop(&newStack, &tmpVal);
// printf("Popped %d\n", tmpVal);
    }
    for(size_t i = 0; i < 15; i++){
        StackPush(&newStack, (int)i + 1);
    }
    
    StackRigid_double* newStackDouble = NewStackRigid_double(1000, stdout);
    for(size_t i = 0; i< 1000; i++){
        StackPush(&newStackDouble, (double)(i));
    }
    for(size_t i = 0; i < 1000; i++){
        double tmpVal;
        StackPop(&newStackDouble, &tmpVal);
// printf("Popped %d\n", tmpVal);
    }
    for(size_t i = 0; i < 15; i++){
        StackPush(&newStackDouble, (double)i + 0.5);
    }
    
    size_t memoryUse = StackRigidMemoryUse(newStack);
    for(size_t i = 0; i < memoryUse; i++){
        char previousValue = *((char*)newStack + i);
        for (char bullet = -128; bullet < 127; bullet++){
            if (bullet == previousValue)
                continue;
            *((char*)newStack + i) = bullet;
            StackRigidState state = StackValidate(newStack);
            if (state != STACK_ST_INTEGRITYERR) {
                printf("Did not spot intervention at position %zu, byte %x\n", i, bullet);
                state = StackValidate(newStack);
                StackDump(newStack);
                break;
            }
        }
        *((char*)newStack + i) = previousValue;
    }
    StackDump(newStack);
    StackDump(newStackDouble);
    *((char*)newStackDouble + 10) = 0xFF;
    StackDump(newStackDouble);
    StackDestruct(&newStack);
    return 0;
}
References STACK_ST_INTEGRITYERR, StackDestruct(), StackDump(), StackPop(), StackPush(), StackRigidMemoryUse(), and StackValidate().
Author
Generated automatically by Doxygen for StackRigid from the source code.