SortedLinesContainer
NAME
SortedLinesContainer
SYNOPSIS
Data Fields
int(* allocate )(struct SortedLinesContainer *this)
Allocates memory so that lines object can contain one more element Uses allocIncrement.
size_t allocIncrement
How much new elements will be allocated when running out of space.
int(* compar )(const void *line1, const void *line2)
Function used in qsort for regular comparison.
int(* comparRev )(const void *line1, const void *line2)
Function used in qsort for comparison from the end of the string.
int(* construct )(struct SortedLinesContainer *this, const char *fullBuffer, const size_t length, const bool fromEnd)
Constructs default object Invisible charecters are trimmed and blank lines are removed.
void(* free )(struct SortedLinesContainer *this)
Frees space.
bool fromEnd
Whether to perform comparison from the end.
char * fullBuffer
Pointer to the start of the string containing substrings separated by \0 (
 replaced by \0) "
char * fullBufferInitial
Pointer to the start of the string containing substrings separated by
 (initial buffer) "
string * lines
Strings containing starts of substrings in fullBuffer.
size_t linesMaxNumber
Number of max elements in lines.
size_t linesNumber
Number of objects in lines.
void(* sort )(struct SortedLinesContainer *this)
Performs sorting of lines array.
Detailed Description
Definition at line 37 of file main.c.
Field Documentation
int(* SortedLinesContainer::allocate) (struct SortedLinesContainer *this)
Allocates memory so that lines object can contain one more element Uses allocIncrement.
Parameters
this [in + out] object to be constructed
Definition at line 113 of file main.c.
Referenced by construct().
size_t SortedLinesContainer::allocIncrement
How much new elements will be allocated when running out of space.
Definition at line 75 of file main.c.
Referenced by allocateContainer().
int(* SortedLinesContainer::compar) (const void *line1, const void *line2)
Function used in qsort for regular comparison.
Parameters
line1 [in] first struct string object
line2 [in] second struct string object
Definition at line 82 of file main.c.
int(* SortedLinesContainer::comparRev) (const void *line1, const void *line2)
Function used in qsort for comparison from the end of the string.
Parameters
line1 [in] first struct string object
line2 [in] second struct string object
Definition at line 89 of file main.c.
int(* SortedLinesContainer::construct) (struct SortedLinesContainer *this, const char *fullBuffer, const size_t length, const bool fromEnd)
Constructs default object Invisible charecters are trimmed and blank lines are removed.
Parameters
this [in + out] object to be constructed
fullBuffer [in] pointer to the first char of readed file
length [in] length of the buffer
fromEnd [in] whether to sort from the end
Definition at line 99 of file main.c.
Referenced by testContainer().
void(* SortedLinesContainer::free) (struct SortedLinesContainer *this)
Frees space.
Parameters
this [in + out] object to be constructed
Definition at line 119 of file main.c.
Referenced by allocateContainer(), construct(), constructFromFile(), freeContainer(), main(), and testContainer().
bool SortedLinesContainer::fromEnd
Whether to perform comparison from the end.
Definition at line 60 of file main.c.
Referenced by construct(), constructFromFile(), sortContainer(), and taskOutput().
char* SortedLinesContainer::fullBuffer
Pointer to the start of the string containing substrings separated by \0 (
 replaced by \0)
Definition at line 42 of file main.c.
Referenced by construct(), and freeContainer().
char* SortedLinesContainer::fullBufferInitial
Pointer to the start of the string containing substrings separated by
 (initial buffer)
Definition at line 48 of file main.c.
Referenced by construct(), and freeContainer().
string* SortedLinesContainer::lines
Strings containing starts of substrings in fullBuffer.
Definition at line 54 of file main.c.
Referenced by allocateContainer(), construct(), constructFromFile(), freeContainer(), sortContainer(), and testContainer().
size_t SortedLinesContainer::linesMaxNumber
Number of max elements in lines.
Definition at line 70 of file main.c.
Referenced by allocateContainer(), and constructFromFile().
size_t SortedLinesContainer::linesNumber
Number of objects in lines.
Definition at line 65 of file main.c.
Referenced by allocateContainer(), construct(), freeContainer(), sortContainer(), and testContainer().
void(* SortedLinesContainer::sort) (struct SortedLinesContainer *this)
Performs sorting of lines array.
Parameters
this [in + out] object to be constructed
Definition at line 106 of file main.c.
Referenced by constructFromFile(), taskOutput(), and testContainer().
Author
Generated automatically by Doxygen for OneginSortv2 from the source code.