StackOnSteroids/StackRigid.cpp
NAME
StackOnSteroids/StackRigid.cpp
SYNOPSIS
#include 'StackRigid.h'
#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
#include <time.h>
Data Structures
struct StackRigid
Macros
#define DEBUGSPEED 1
If defined, collects average speed information during the run.
Functions
static uint32_t __StackGetChecksum (StackRigid *stack)
static uint32_t __StackGetChecksumVital (StackRigid *stack)
static StackRigidOperationCodes __StackRealocate (StackRigid **stack, short int direction)
static void __StackUpdateChecksum (StackRigid *stack)
static uint32_t adlerChecksum (const void *firstBlock, size_t len)
StackRigid * NewStackRigid (const size_t capacity, FILE *logFile)
Create new stack with pre-defined capacity.
StackRigidOperationCodes StackBack (StackRigid *stack, StackElementType *value)
Free stack memory.
StackRigidOperationCodes StackDestruct (StackRigid **stack)
Free stack memory.
void StackDump (StackRigid *stack)
Dumps debug information about the stack.
StackRigidOperationCodes StackPop (StackRigid **stack, StackElementType *value)
Pop value from the end of the stack The operation can perform realocations if there is too much space.
StackRigidOperationCodes StackPush (StackRigid **stack, StackElementType value)
Push the value to the stack The operation can perform realocations if there is not enough space.
size_t StackRigidMemoryUse (StackRigid *stack)
Memory alocated for the Stack.
StackRigidState StackValidate (StackRigid *stack)
Perform all stack checks: checksums, general constrains.
Variables
const double movingAverageBetta = 0.85
double StackRigidAvgTimes [5] = {}
Macro Definition Documentation
#define DEBUGSPEED 1
If defined, collects average speed information during the run.
Function Documentation
static uint32_t __StackGetChecksum (StackRigid * stack) [static]
                                                      {
    assert(stack);
    
    void* firstBlock = (char*)stack + sizeof(stack->checkSum);
    
    // Memory used by Stack excluding checkSum and free space
    const size_t memory = StackRigidMemoryUse(stack) - sizeof(stack->checkSum) - (stack->capacity - stack->size) * sizeof(StackElementType);
    
    if (stack->size > stack->capacity) {
        return 0;
    }
    return adlerChecksum(firstBlock, memory);
}
References adlerChecksum(), StackRigid::capacity, StackRigid::checkSum, StackRigid::size, and StackRigidMemoryUse().
Referenced by __StackUpdateChecksum(), and StackValidate().
static uint32_t __StackGetChecksumVital (StackRigid * stack) [static]
                                                           {
    assert(stack);
    
    void* firstBlock = (char*)stack + sizeof(stack->checkSum) + sizeof(stack->checkSumVital);
    
    const size_t memory = sizeof(stack->size) + sizeof(stack->capacity)+ sizeof(stack->logFile);
    if (stack->size > stack->capacity) {
        return 0;
    }
    return adlerChecksum(firstBlock, memory);
}
References adlerChecksum(), StackRigid::capacity, StackRigid::checkSum, StackRigid::checkSumVital, StackRigid::logFile, and StackRigid::size.
Referenced by __StackUpdateChecksum(), and StackValidate().
static StackRigidOperationCodes __StackRealocate (StackRigid ** stack, short int direction) [static]
                                                                                          {
    #ifdef DEBUGSPEED
        clock_t start = clock();
    #endif
    if ((*stack)->capacity == 0) {
        (*stack)->capacity = 16;
        
        const size_t memory = StackRigidMemoryUse(*stack);
        
        StackRigid* newStack = (StackRigid*) realloc((*stack), memory);
        if (newStack == NULL)
            return STACK_OP_NOMEMORY;
        
        (*stack) = newStack;
    }else if(((*stack)->capacity <= (*stack)->size) && direction > 0) {
        // Up realocation
        size_t newCapacity = (*stack)->size * 2;
        
        if (newCapacity <= (*stack)->size) { // If we exceeded size_t range
            newCapacity = (*stack)->size + 16; // Try to add 16 free spaces
            if (newCapacity < (*stack)->size) // Even if in this case we still exceed size_t
                return STACK_OP_OVERFLOW;
        }
        
        const size_t memoryNow = StackRigidMemoryUse(*stack);
        const size_t memoryNew = sizeof(StackRigid) + (newCapacity - 2) * sizeof(StackElementType);
        
        if (memoryNew >= memoryNow) {
            StackRigid* newStack = (StackRigid*) realloc((*stack), memoryNew);
            if (newStack == NULL)
                return STACK_OP_NOMEMORY;
            
            (*stack) = newStack;
        }else{
            return STACK_OP_OVERFLOW; // Exceded size_t memory
        }
        (*stack)->capacity = newCapacity;
        
    }else if (((*stack)->capacity / 2.2 > (*stack)->size) && direction < 0) {
        // Down realocation
        size_t newCapacity = (*stack)->capacity / 2.2;
        
        const size_t memoryNow = StackRigidMemoryUse(*stack);
        const size_t memoryNew = sizeof(StackRigid) + (newCapacity - 2) * sizeof(StackElementType);
        
        if (memoryNew <= memoryNow) {
            StackRigid* newStack = (StackRigid*) realloc((*stack), memoryNew);
            if (newStack == NULL)
                return STACK_OP_NOMEMORY;
            
            (*stack) = newStack;
            (*stack)->capacity = newCapacity;
        }else
            return STACK_OP_OVERFLOW; // Exceded size_t memory
    }
    #ifdef DEBUGSPEED
        clock_t end = clock();
        double elapsed = (double)(end - start) / CLOCKS_PER_SEC;
        StackRigidAvgTimes[4] = StackRigidAvgTimes[4] * (movingAverageBetta) + elapsed * (1 - movingAverageBetta);
    #endif
    return STACK_OP_OK;
}
References StackRigid::capacity, movingAverageBetta, StackRigid::size, STACK_OP_NOMEMORY, STACK_OP_OK, STACK_OP_OVERFLOW, StackRigidAvgTimes, and StackRigidMemoryUse().
Referenced by StackPop(), and StackPush().
static void __StackUpdateChecksum (StackRigid * stack) [static]
                                                     {
    assert(stack);
    
    #ifdef DEBUGSPEED
        clock_t start = clock();
    #endif
    
    stack->checkSumVital = __StackGetChecksumVital(stack);
    stack->checkSum = __StackGetChecksum(stack);
    
    #ifdef DEBUGSPEED
        clock_t end = clock();
        double elapsed = (double)(end - start) / CLOCKS_PER_SEC;
    
        StackRigidAvgTimes[0] = StackRigidAvgTimes[0] * (movingAverageBetta) + elapsed * (1 - movingAverageBetta);
    #endif
}
References __StackGetChecksum(), __StackGetChecksumVital(), StackRigid::checkSum, StackRigid::checkSumVital, movingAverageBetta, and StackRigidAvgTimes.
Referenced by NewStackRigid(), StackPop(), and StackPush().
static uint32_t adlerChecksum (const void * firstBlock, size_t len) [static]
                                                                  {
    uint32_t a = 1, b = 0;
    const uint32_t MOD_ADLER = 65521;
    for (size_t index = 0; index < len; ++index) {
        a = (a + ((char*)firstBlock)[index]) % MOD_ADLER;
        b = (b + a) % MOD_ADLER;
    }
    return (b << 16) | a;
}
Referenced by __StackGetChecksum(), and __StackGetChecksumVital().
StackRigid* NewStackRigid (const size_t capacity, FILE * logFile)
Create new stack with pre-defined capacity.
Parameters
capacity initial stack capacity. Set to 0 if yo want the stack to adopt automaticaly.
logFile file for logging
Returns
new stack pointer
                                                                {
    const size_t memory = sizeof(StackRigid) + (capacity - 2) * sizeof(StackElementType);
    StackRigid* pointer = (StackRigid*)calloc(memory, 1);
    if (pointer == NULL) {
        return NULL;
    }
    
    pointer->capacity = capacity;
    pointer->size = 0;
    pointer->logFile = logFile;
    pointer->checkSum = 0;
    pointer->checkSumVital = 0;
    __StackUpdateChecksum(pointer);
    return pointer;
}
References __StackUpdateChecksum(), StackRigid::capacity, StackRigid::checkSum, StackRigid::checkSumVital, StackRigid::logFile, and StackRigid::size.
Referenced by main().
StackRigidOperationCodes StackBack (StackRigid * stack, StackElementType * value)
Free stack memory.
Parameters
stack Stack to be used
Returns
the outcome of the operation
                                                                              {
    if (stack == NULL)
        return STACK_OP_NULL;
    
    StackRigidState integrityChecks = StackValidate(stack);
    if (integrityChecks != STACK_ST_OK) {
        StackDump(stack);
        return STACK_OP_INTEGRITYERR;
    }
    
    if(stack->size == 0)
        return STACK_OP_UNDERFLOW;
    
    *value = stack->data[stack->size - 1];
    return STACK_OP_OK;
}
References StackRigid::data, StackRigid::size, STACK_OP_INTEGRITYERR, STACK_OP_NULL, STACK_OP_OK, STACK_OP_UNDERFLOW, STACK_ST_OK, StackDump(), and StackValidate().
StackRigidOperationCodes StackDestruct (StackRigid ** stack)
Free stack memory.
Parameters
stack Stack to be distructed
Returns
the outcome of the operation
                                                           {
    if (stack == NULL) {
        return STACK_OP_NULL;
    }
    if (*stack == NULL) {
        return STACK_OP_NULL;
    }
    free(*stack);
    return STACK_OP_OK;
}
References STACK_OP_NULL, and STACK_OP_OK.
Referenced by main().
void StackDump (StackRigid * stack)
Dumps debug information about the stack.
Parameters
stack Stack to be dumped
                                  {
    time_t rawtime = time(NULL);
    struct tm *ptm = localtime(&rawtime);
    
    FILE* output = stack->logFile;
    if (output == NULL) {
        output = stdout;
        printf("\nWarning! Specified dump output is inavailbale! Selecting stdout.\n");
    }
    
    fprintf(output, "=================================\n");
    fprintf(output, "Stack dump %s", asctime(ptm));
    
    if (stack == NULL) {
        fprintf(output, "\nStack dump is impossible: NULL pointer\n");
    }else{
        fprintf(output, "Stack (");
        const char *status = "ok";
        StackRigidState checks = StackValidate(stack);
        switch (checks) {
            case STACK_ST_INTEGRITYERR:
                status = "INTEGRITY ERROR SPOTTED";
                break;
            case STACK_ST_UNINITIALIZED:
                status = "UNINITIALIZED";
                break;
            case STACK_ST_OK:
                status = "ok";
                break;
            case STACK_ST_NULL:
                status = "NULL POINTER";
                break;
        }
        fprintf(output, "%s", status);
        fprintf(output, ")");
        fprintf(output, " [%p]: {\n", stack);
        if (checks == STACK_ST_INTEGRITYERR) {
            fprintf(output, "ERROR! Stack structure was corrupted. The data below was changed from the outside.\n");
        }
        fprintf(output, "\t size : %lu\n", stack->size);
        fprintf(output, "\tcapacity : %lu\n", stack->capacity);
        fprintf(output, "\tcheckSum : %x\n", stack->checkSum);
        
        fprintf(output, "\tdata [%p]: {\n", stack->data);
        size_t i = 0;
        for (i = 0; i < stack->size; i++) {
            fprintf(output, "\t\t");
            fprintf(output, "*[%lu] : %d\n", i, stack->data[i]);
        }
        fprintf(output, "\t\t _______\n");
        if (stack->size < stack->capacity) {
            fprintf(output, "\t\t [%lu] : GARBAGE(%d)\n", i + 1, stack->data[i + 1]);
        }
        if (stack->size + 1 < stack->capacity && stack->size + 1 > stack->size) {
            fprintf(output, "\t\t [%lu] : GARBAGE(%d)\n", i + 2, stack->data[i + 2]);
        }
        fprintf(output, "\t}\n");
        fprintf(output, "}\n");
        
        const size_t memory = StackRigidMemoryUse(stack);
        fprintf(output, "Size allocated : %lu bytes\n", memory);
        fprintf(output, "Raw Stack size : %lu bytes\n", sizeof(StackRigid));
        fprintf(output, " Element size : %lu bytes\n", sizeof(StackElementType));
        fprintf(output, " Block end : %p\n", (char*)stack + memory);
    }
    fprintf(output, "=================================\n");
}
References StackRigid::capacity, StackRigid::checkSum, StackRigid::data, StackRigid::logFile, StackRigid::size, STACK_ST_INTEGRITYERR, STACK_ST_NULL, STACK_ST_OK, STACK_ST_UNINITIALIZED, StackRigidMemoryUse(), and StackValidate().
Referenced by StackBack(), StackPop(), and StackPush().
StackRigidOperationCodes StackPop (StackRigid ** stack, StackElementType * value)
Pop value from the end of the stack The operation can perform realocations if there is too much space.
Parameters
stack Stack to be distructed
value value to be pushed
Returns
the outcome of the operation
                                                                               {
    #ifdef DEBUGSPEED
        clock_t start = clock();
    #endif
    
    if (stack == NULL)
        return STACK_OP_NULL;
    
    StackRigidState integrityChecks = StackValidate(*stack);
    if (integrityChecks != STACK_ST_OK) {
        StackDump(*stack);
        return STACK_OP_INTEGRITYERR;
    }
    
    if((*stack)->size == 0)
        return STACK_OP_UNDERFLOW;
    
    *value = (*stack)->data[(*stack)->size - 1];
    (*stack)->size -= 1;
    
    __StackRealocate(stack, -1);
    __StackUpdateChecksum(*stack);
    
    #ifdef DEBUGSPEED
        clock_t end = clock();
        double elapsed = (double)(end - start) / CLOCKS_PER_SEC;
        StackRigidAvgTimes[3] = StackRigidAvgTimes[3] * (movingAverageBetta) + elapsed * (1 - movingAverageBetta);
    #endif
    
    return STACK_OP_OK;
}
References __StackRealocate(), __StackUpdateChecksum(), movingAverageBetta, STACK_OP_INTEGRITYERR, STACK_OP_NULL, STACK_OP_OK, STACK_OP_UNDERFLOW, STACK_ST_OK, StackDump(), StackRigidAvgTimes, and StackValidate().
Referenced by main().
StackRigidOperationCodes StackPush (StackRigid ** stack, StackElementType value)
Push the value to the stack The operation can perform realocations if there is not enough space.
Parameters
stack Stack to be changed
value value to be pushed
Returns
the outcome of the operation
                                                                               {
    #ifdef DEBUGSPEED
        clock_t start = clock();
    #endif
    if (stack == NULL)
        return STACK_OP_NULL;
    
    StackRigidState integrityChecks = StackValidate(*stack);
    if (integrityChecks != STACK_ST_OK) {
        StackDump(*stack);
        return STACK_OP_INTEGRITYERR;
    }
    
    StackRigidOperationCodes realocResult = __StackRealocate(stack, 1);
    if (realocResult != STACK_OP_OK) {
        StackDump(*stack);
        return realocResult;
    }
    
    (*stack)->data[(*stack)->size] = value;
    (*stack)->size += 1;
    
    __StackUpdateChecksum(*stack);
    
    if ((*stack)->size == 0) {
        return STACK_OP_OVERFLOW;
    }
    #ifdef DEBUGSPEED
        clock_t end = clock();
        double elapsed = (double)(end - start) / CLOCKS_PER_SEC;
        StackRigidAvgTimes[2] = StackRigidAvgTimes[2] * (movingAverageBetta) + elapsed * (1 - movingAverageBetta);
    #endif
    return STACK_OP_OK;
}
References __StackRealocate(), __StackUpdateChecksum(), movingAverageBetta, STACK_OP_INTEGRITYERR, STACK_OP_NULL, STACK_OP_OK, STACK_OP_OVERFLOW, STACK_ST_OK, StackDump(), StackRigidAvgTimes, and StackValidate().
Referenced by main().
size_t StackRigidMemoryUse (StackRigid * stack)
Memory alocated for the Stack.
Parameters
stack Stack to be checked
Returns
alocated bytes
                                              {
    assert(stack);
    return sizeof(StackRigid) + (stack->capacity - 2) * sizeof(StackElementType);
}
References StackRigid::capacity.
Referenced by __StackGetChecksum(), __StackRealocate(), main(), and StackDump().
StackRigidState StackValidate (StackRigid * stack)
Perform all stack checks: checksums, general constrains.
Parameters
stack Stack to be validated
Returns
calculated state
                                                 {
    #ifdef DEBUGSPEED
        clock_t start = clock();
    #endif
    
    if (stack == NULL)
        return STACK_ST_NULL;
    
    if (stack->size > stack->capacity || stack->checkSum == 0 || stack->checkSumVital == 0)
        return STACK_ST_INTEGRITYERR;
    
    uint32_t currentChecksumVital = __StackGetChecksumVital(stack);
    if (currentChecksumVital != stack->checkSumVital || currentChecksumVital == 0)
        return STACK_ST_INTEGRITYERR;
    
    uint32_t currentChecksum = __StackGetChecksum(stack);
    if (currentChecksum != stack->checkSum || currentChecksum == 0)
        return STACK_ST_INTEGRITYERR;
    
    #ifdef DEBUGSPEED
        clock_t end = clock();
        double elapsed = (double)(end - start) / CLOCKS_PER_SEC;
        StackRigidAvgTimes[1] = StackRigidAvgTimes[1] * (movingAverageBetta) + elapsed * (1 - movingAverageBetta);
    #endif
    return STACK_ST_OK;
}
References __StackGetChecksum(), __StackGetChecksumVital(), StackRigid::capacity, StackRigid::checkSum, StackRigid::checkSumVital, movingAverageBetta, StackRigid::size, STACK_ST_INTEGRITYERR, STACK_ST_NULL, STACK_ST_OK, and StackRigidAvgTimes.
Referenced by main(), StackBack(), StackDump(), StackPop(), and StackPush().
Variable Documentation
const double movingAverageBetta = 0.85
Referenced by __StackRealocate(), __StackUpdateChecksum(), StackPop(), StackPush(), and StackValidate().
double StackRigidAvgTimes[5] = {}
Referenced by __StackRealocate(), __StackUpdateChecksum(), main(), StackPop(), StackPush(), and StackValidate().
Author
Generated automatically by Doxygen for StackRigid from the source code.