StackOnSteroids/StackRigid.h
NAME
StackOnSteroids/StackRigid.h
SYNOPSIS
#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
#include <time.h>
#include 'PointerChecks.h'
Macros
#define __overload(FUNC) EVALUATOR(FUNC, StackElementType)
#define EVALUATOR(x, y) PASTER(x,y)
#define PASTER(x, y) x ## _ ## y
#define StackDumpWrapper(stack) { StackDump(stack, __LINE__, __FILE__, ''); }
#define StackDumpWrapperWhy(stack, why) { StackDump(stack, __LINE__, __FILE__, why); }
#define StackElementDump(FILE, VALUE) {fprintf(FILE, '%d', VALUE);}
Default element dump instruction.
#define StackElementType int
By default, it will be stack of ints.
#define StackRigid_h
Typedefs
typedef enum StackRigidOperationCodes StackRigidOperationCodes
Codes returned after operations on Stack.
typedef enum StackRigidState StackRigidState
Codes characterizing Stack state.
Enumerations
enum StackRigidOperationCodes { STACK_OP_OK, STACK_OP_UNDERFLOW, STACK_OP_OVERFLOW, STACK_OP_NOMEMORY, STACK_OP_INTEGRITYERR, STACK_OP_NULL, STACK_OP_PTRINVALID }
Codes returned after operations on Stack.
enum StackRigidState { STACK_ST_OK, STACK_ST_INTEGRITYERR, STACK_ST_UNINITIALIZED, STACK_ST_NULL }
Codes characterizing Stack state.
Functions
struct __overload (StackRigid) = ( __overload(StackRigid)*)calloc(memory, 1)
The main StackRigid struct.
static uint32_t __StackGetChecksum (__overload(StackRigid) *stack)
Claculates big Stack checksum. Uses Adler-32 method.
static uint32_t __StackGetChecksumVital (__overload(StackRigid) *stack)
Uses Adler-32 method. Calculates Stack checksum only for the vital parameters. This is necessary because __StackGetChecksum() relies on capacity and size. If they were changed, behaviour is undefined.
static StackRigidOperationCodes __StackReallocate (__overload(StackRigid) **stack, short int direction)
Reallocates Stack if needed.
static void __StackUpdateChecksum (__overload(StackRigid) *stack)
Updates Stack checksums. Does not take into account bytes inside the stack but outside of its last element.
__StackUpdateChecksum (pointer)
static uint32_t adlerChecksum (const void *firstBlock, size_t len)
Calculates Adler-32 checksum from the firstBlock to the firstBlock + len.
if (!istack_pointer_valid(logFile, sizeof(logFile)))
if (!istack_pointer_valid(pointer, sizeof(pointer)))
if (added< memory)
StackRigidOperationCodes StackBack (__overload(StackRigid) *stack, StackElementType *value)
Free stack memory.
StackRigidOperationCodes StackDestruct (__overload(StackRigid) **stack)
Free stack memory.
void StackDump (__overload(StackRigid) *stack, const int line, const char *file, const char *why)
Dumps debug information about the stack.
StackRigidOperationCodes StackPop (__overload(StackRigid) **stack, StackElementType *value)
Pop value from the end of the stack The operation can perform reallocations if there is too much space.
StackRigidOperationCodes StackPush (__overload(StackRigid) **stack, StackElementType value)
Push the value to the stack The operation can perform reallocations if there is not enough space.
size_t StackRigidMemoryUse (__overload(StackRigid) *stack)
Memory alocated for the Stack.
StackRigidState StackValidate (__overload(StackRigid) *stack)
Perform all stack checks: checksums, general constrains.
Variables
size_t added = memory + (capacity - 1) * sizeof(StackElementType)
pointer capacity = capacity
pointer checkSum = 0
pointer checkSumVital = 0
FILE * logFile
size_t memory = sizeof( __overload(StackRigid))
return pointer
pointer size = 0
Macro Definition Documentation
#define __overload(FUNC) EVALUATOR(FUNC, StackElementType)
#define EVALUATOR(x, y) PASTER(x,y)
#define PASTER(x, y) x ## _ ## y
#define StackDumpWrapper(stack) { StackDump(stack, __LINE__, __FILE__, ''); }
#define StackDumpWrapperWhy(stack, why) { StackDump(stack, __LINE__, __FILE__, why); }
#define StackElementDump(FILE, VALUE) {fprintf(FILE, '%d', VALUE);}
Default element dump instruction.
#define StackElementType int
By default, it will be stack of ints.
#define StackRigid_h
Typedef Documentation
typedef enum StackRigidOperationCodes StackRigidOperationCodes
Codes returned after operations on Stack.
typedef enum StackRigidState StackRigidState
Codes characterizing Stack state.
Enumeration Type Documentation
enum StackRigidOperationCodes
Codes returned after operations on Stack.
Enumerator
STACK_OP_OK
Succesful operation.
STACK_OP_UNDERFLOW
Tried to get value from the empty stack.
STACK_OP_OVERFLOW
Stack overflow and new memory allocation failed.
STACK_OP_NOMEMORY
No memory for stack alocations.
STACK_OP_INTEGRITYERR
Stack memory was altered by some outer access.
STACK_OP_NULL
Found NULL pointer during the operation.
STACK_OP_PTRINVALID
Found invalid pointer during the operation.
                                     {
    STACK_OP_OK,
    STACK_OP_UNDERFLOW,
    STACK_OP_OVERFLOW,
    STACK_OP_NOMEMORY,
    STACK_OP_INTEGRITYERR,
    STACK_OP_NULL,
    STACK_OP_PTRINVALID
} StackRigidOperationCodes;
enum StackRigidState
Codes characterizing Stack state.
Enumerator
STACK_ST_OK
Stack is running as expected.
STACK_ST_INTEGRITYERR
Stack was altered by some outer access.
STACK_ST_UNINITIALIZED
Stack is uninitialized.
STACK_ST_NULL
Found NULL pointer during the operation.
                            {
    STACK_ST_OK,
    STACK_ST_INTEGRITYERR,
    STACK_ST_UNINITIALIZED,
    STACK_ST_NULL
} StackRigidState;
Function Documentation
__overload (StackRigid) = ( __overload(StackRigid)*)calloc(memory, 1)
The main StackRigid struct. Create new stack with pre-defined capacity.
Parameters
capacity initial stack capacity. Set to 0 if you want the stack to adopt automaticaly.
logFile file for logging
Returns
new stack pointer or NULL if impossible
                              {
    uint32_t checkSum;
    uint32_t checkSumVital;
    size_t capacity;
    size_t size;
    FILE* logFile;
    StackElementType data[1];
};
static uint32_t __StackGetChecksum (__overload(StackRigid) * stack) [static]
Claculates big Stack checksum. Uses Adler-32 method.
Attention
Not for the manual use!
* Stack memory : [ checkSum checkSumVital capacity size logFile | value 1, value 2, ..., value n || ___garbage area___]
* Release:
* ________________from here ^__________________________________________________________^to here
* Debug:
* ________________from here ^______________________________________________________________________________^to here
*
Parameters
stack Stack that checksums are needed to be updated
                                                                   {
    assert(stack);
    
    void* firstBlock = (char*)stack + sizeof(stack->checkSum);
    
    // Memory used by Stack excluding checkSum and free space
    #ifndef DEBUG
        const size_t memory = StackRigidMemoryUse(stack) - sizeof(stack->checkSum) - (stack->capacity - stack->size) * sizeof(StackElementType);
    #endif
    #ifdef DEBUG
        const size_t memory = StackRigidMemoryUse(stack) - sizeof(stack->checkSum);
    #endif
    
    if (stack->size > stack->capacity) {
        return 0;
    }
    return adlerChecksum(firstBlock, memory);
}
References adlerChecksum(), memory, StackElementType, and StackRigidMemoryUse().
Referenced by __StackUpdateChecksum(), and StackValidate().
static uint32_t __StackGetChecksumVital (__overload(StackRigid) * stack) [static]
Uses Adler-32 method. Calculates Stack checksum only for the vital parameters. This is necessary because __StackGetChecksum() relies on capacity and size. If they were changed, behaviour is undefined.
Attention
Not for the manual use!
* Stack memory : [ checkSum checkSumVital capacity size logFile | value 1, value 2, ..., value n || ___garbage area___]
* ______________________________from here ^__________________^to here
* .fi
 
Parameters
stack Stack that checksums are needed to be updated
                                                                        {
    assert(stack);
    
    void* firstBlock = (char*)stack + sizeof(stack->checkSum) + sizeof(stack->checkSumVital);
    
    const size_t memory = (size_t)((char*)(stack->data) - (char*)firstBlock);
    if (stack->size > stack->capacity) {
        return 0;
    }
    return adlerChecksum(firstBlock, memory);
}
References adlerChecksum(), and memory.
Referenced by __StackUpdateChecksum(), and StackValidate().
static StackRigidOperationCodes __StackReallocate (__overload(StackRigid) ** stack, short int direction) [static]
Reallocates Stack if needed.
Attention
Not for the manual use!
Parameters
stack Stack to be reallocated
direction which direction reallocations are available. > 0 -> expand space if needed, < 0 -> shrink space if needed
                                                                                                        {
    if ((*stack)->capacity == 0) {
        (*stack)->capacity = 16; // capacity if was 0
        
        const size_t memory = StackRigidMemoryUse(*stack);
        
         __overload(StackRigid)* newStack = ( __overload(StackRigid)*) realloc((*stack), memory);
        if (!istack_pointer_valid(newStack, sizeof(newStack)))
            return STACK_OP_NOMEMORY;
        
        (*stack) = newStack;
    }else if(((*stack)->capacity <= (*stack)->size) && direction > 0) { // Up reallocation
        size_t newCapacity = (*stack)->size * 2;
        
        if (newCapacity <= (*stack)->size) { // If we exceeded size_t range
            newCapacity = (*stack)->size + 16; // Try to add 16 free spaces
            if (newCapacity < (*stack)->size) // Even if in this case we still exceed size_t
                return STACK_OP_OVERFLOW;
        }
        
        const size_t memoryNow = StackRigidMemoryUse(*stack);
        const size_t memoryNew = sizeof(__overload(StackRigid)) + (newCapacity - 1) * sizeof(StackElementType);
        
        if (memoryNew >= memoryNow) {
             __overload(StackRigid)* newStack = ( __overload(StackRigid)*) realloc((*stack), memoryNew);
            if (!istack_pointer_valid(newStack, sizeof(newStack)))
                return STACK_OP_NOMEMORY;
            
            (*stack) = newStack;
        }else{
            return STACK_OP_OVERFLOW; // Exceded size_t memory
        }
        (*stack)->capacity = newCapacity;
        
    }else if (((*stack)->capacity / 2.2 > (*stack)->size) && direction < 0) { // Down reallocation
        size_t newCapacity = (*stack)->capacity / 2.2;
        
        const size_t memoryNow = StackRigidMemoryUse(*stack);
        const size_t memoryNew = sizeof(__overload(StackRigid)) + (newCapacity - 1) * sizeof(StackElementType);
        
        if (memoryNew <= memoryNow) {
             __overload(StackRigid)* newStack = ( __overload(StackRigid)*) realloc((*stack), memoryNew);
            if (!istack_pointer_valid(newStack, sizeof(newStack)))
                return STACK_OP_NOMEMORY;
            
            (*stack) = newStack;
            (*stack)->capacity = newCapacity;
        }else
            return STACK_OP_OVERFLOW; // Exceded size_t memory
    }
    return STACK_OP_OK;
}
References __overload, memory, STACK_OP_NOMEMORY, STACK_OP_OK, STACK_OP_OVERFLOW, StackElementType, and StackRigidMemoryUse().
Referenced by StackPop(), and StackPush().
static void __StackUpdateChecksum (__overload(StackRigid) * stack) [static]
Updates Stack checksums. Does not take into account bytes inside the stack but outside of its last element.
Attention
Not for the manual use!
* Stack memory : [ __stack area__ | value 1, value 2, ..., value n || ___garbage area___]
* ____________________________________________________________________^ alterations in this area are not checked
*
Parameters
stack Stack that checksums are needed to be updated
                                                                  {
    assert(stack);
    #ifndef IGNORE_VALIDITY
        stack->checkSumVital = __StackGetChecksumVital(stack);
        stack->checkSum = __StackGetChecksum(stack);
    #endif
}
References __StackGetChecksum(), and __StackGetChecksumVital().
Referenced by StackPop(), and StackPush().
__StackUpdateChecksum (pointer)
static uint32_t adlerChecksum (const void * firstBlock, size_t len) [static]
Calculates Adler-32 checksum from the firstBlock to the firstBlock + len.
Attention
Not for the manual use!
Parameters
firstBlock first block to include to the checksum
len length of byte sequence
Returns
checksum
                                                                  {
    uint32_t a = 1, b = 0;
    const uint32_t MOD_ADLER = 65521;
    for (size_t index = 0; index < len; ++index) {
        a = (a + ((unsigned char*)firstBlock)[index]) % MOD_ADLER;
        b = (b + a) % MOD_ADLER;
    }
    return (b << 16) | a;
}
Referenced by __StackGetChecksum(), and __StackGetChecksumVital().
if (! istack_pointer_validlogFile, sizeof(logFile))
                                                          {
         return NULL;
     }
if (! istack_pointer_validpointer, sizeof(pointer))
                                                         {
        return NULL;
    }
if ()
                         {
         return NULL;
     }
StackRigidOperationCodes StackBack (__overload(StackRigid) * stack, StackElementType * value)
Free stack memory.
Parameters
stack Stack to be used
Returns
the outcome of the operation
                                                                                           {
    if (!istack_pointer_valid(stack, sizeof(stack)))
        return STACK_OP_NULL;
    
    
    StackRigidState integrityChecks = StackValidate(stack);
    
    if (integrityChecks != STACK_ST_OK) {
        StackDumpWrapperWhy(stack, "StackBack operation spotted integrity error");
        return STACK_OP_INTEGRITYERR;
    }
    
    if(stack->size == 0)
        return STACK_OP_UNDERFLOW;
    
    *value = stack->data[stack->size - 1];
    return STACK_OP_OK;
}
References STACK_OP_INTEGRITYERR, STACK_OP_NULL, STACK_OP_OK, STACK_OP_UNDERFLOW, STACK_ST_OK, StackDumpWrapperWhy, and StackValidate().
StackRigidOperationCodes StackDestruct (__overload(StackRigid) ** stack)
Free stack memory.
Parameters
stack Stack to be distructed
Returns
the outcome of the operation
                                                                        {
    if (!istack_pointer_valid(stack, sizeof(stack))) {
        return STACK_OP_NULL;
    }
    if (!istack_pointer_valid(*stack, sizeof(*stack))) {
        return STACK_OP_NULL;
    }
    StackRigidState checks = StackValidate(*stack);
    if (checks == STACK_ST_OK){
        const size_t memoryNow = StackRigidMemoryUse(*stack);
        for(char* cursor = (char*)(*stack); cursor < (char*)(*stack) + memoryNow; cursor++)
            *cursor = 0;
    }
    free(*stack);
    return STACK_OP_OK;
}
References STACK_OP_NULL, STACK_OP_OK, STACK_ST_OK, StackRigidMemoryUse(), and StackValidate().
Referenced by main().
void StackDump (__overload(StackRigid) * stack, const int line, const char * file, const char * why)
Dumps debug information about the stack.
Parameters
stack Stack to be dumped
                                                                                                  {
    time_t rawtime = time(NULL);
    struct tm *ptm = localtime(&rawtime);
    
    if (!istack_pointer_valid(stack, sizeof(stack))){
        fprintf(stdin, "\nStack dump is impossible: NULL pointer\n");
        return;
    }
    
    FILE* output = stack->logFile;
    if (!istack_pointer_valid(output, sizeof(output))) {
        output = stdout;
        printf("\nWarning! Specified dump output is inavailbale! Selecting stdout.\n");
    }
    
    fprintf(output, "=================================\n");
    fprintf(output, "Stack dump %s", asctime(ptm));
    fprintf(output, "Line: %d\nFile: %s\n", line, file);
    if (why[0] != '\0')
    fprintf(output, "Problem: %s\n", why);
    
    if (istack_pointer_valid(stack, sizeof(stack))) {
        fprintf(output, "Stack (");
        const char *status = "ok";
        StackRigidState checks = StackValidate(stack);
        switch (checks) {
            case STACK_ST_INTEGRITYERR:
                status = "INTEGRITY ERROR SPOTTED";
                break;
            case STACK_ST_UNINITIALIZED:
                status = "UNINITIALIZED";
                break;
            case STACK_ST_OK:
                status = "ok";
                break;
            case STACK_ST_NULL:
                status = "NULL POINTER";
                break;
        }
        fprintf(output, "%s", status);
        fprintf(output, ")");
        fprintf(output, " [%p]: {\n", stack);
        if (checks != STACK_ST_OK) {
            fprintf(output, "ERROR! Stack structure was corrupted.\nThe data below was changed from the outside.\nThis can fail!\n");
        }
        fprintf(output, "\t size : %lu\n", stack->size);
        fprintf(output, "\t capacity : %lu\n", stack->capacity);
        fprintf(output, "\t checkSum : %x\n", stack->checkSumVital);
        fprintf(output, "\tcheckSumVital : %x\n", stack->checkSum);
        
        fprintf(output, "\tdata [%p]: {\n", stack->data);
        if (checks == STACK_ST_OK) {
        size_t i = 0;
        for (i = 0; i < stack->size; i++) {
            fprintf(output, "\t\t");
            fprintf(output, "*[%lu] : ", i);
            fprintf(output, "[%p] ", stack->data + i);
            StackElementDump(stack->logFile, stack->data[i]);
            fprintf(output, "\n");
        }
        fprintf(output, "\t\t _______\n");
        if (stack->size < stack->capacity) {
            fprintf(output, "\t\t [%lu] : GARBAGE(", i);
            fprintf(output, "[%p] ", stack->data + i);
            StackElementDump(stack->logFile, stack->data[i]);
            fprintf(output, ")\n");
        }
        if (stack->size + 1< stack->capacity && stack->size + 1 > stack->size) {
            fprintf(output, "\t\t [%lu] : GARBAGE(", i + 1);
            fprintf(output, "[%p] ", stack->data + i + 1);
            StackElementDump(stack->logFile, stack->data[i + 1]);
            fprintf(output, ")\n");
        }
        } else{
            fprintf(output, "\t\tDATA CAN'T BE READED\n");
        }
        
        fprintf(output, "\t}\n");
        fprintf(output, "}\n");
        
        const size_t memory = StackRigidMemoryUse(stack);
        fprintf(output, "Size allocated : %lu bytes\n", memory);
        fprintf(output, "Raw Stack size : %lu bytes\n", sizeof(__overload(StackRigid)));
        fprintf(output, " Element size : %lu bytes\n", sizeof(StackElementType));
        fprintf(output, " Block end : %p\n", (char*)stack + memory);
    }
    fprintf(output, "=================================\n");
    fflush(NULL);
    
}
References __overload, memory, STACK_ST_INTEGRITYERR, STACK_ST_NULL, STACK_ST_OK, STACK_ST_UNINITIALIZED, StackElementDump, StackElementType, StackRigidMemoryUse(), and StackValidate().
StackRigidOperationCodes StackPop (__overload(StackRigid) ** stack, StackElementType * value)
Pop value from the end of the stack The operation can perform reallocations if there is too much space.
Parameters
stack Stack to be distructed
value value to be pushed
Returns
the outcome of the operation
                                                                                            {
    if (!istack_pointer_valid(stack, sizeof(stack)))
        return STACK_OP_NULL;
    
    StackRigidState integrityChecks = StackValidate(*stack);
    
    if (integrityChecks != STACK_ST_OK) {
        StackDumpWrapperWhy(*stack, "StackPop operation spotted integrity error");
        return STACK_OP_INTEGRITYERR;
    }
    
    if((*stack)->size == 0)
        return STACK_OP_UNDERFLOW;
    
    *value = (*stack)->data[(*stack)->size - 1];
    (*stack)->size -= 1;
    
    __StackReallocate(stack, -1);
    __StackUpdateChecksum(*stack);
    return STACK_OP_OK;
}
References __StackReallocate(), __StackUpdateChecksum(), STACK_OP_INTEGRITYERR, STACK_OP_NULL, STACK_OP_OK, STACK_OP_UNDERFLOW, STACK_ST_OK, StackDumpWrapperWhy, and StackValidate().
Referenced by main().
StackRigidOperationCodes StackPush (__overload(StackRigid) ** stack, StackElementType value)
Push the value to the stack The operation can perform reallocations if there is not enough space.
Parameters
stack Stack to be changed
value value to be pushed
Returns
the outcome of the operation
                                                                                           {
    if (!istack_pointer_valid(stack, sizeof(stack)))
        return STACK_OP_PTRINVALID;
    if (!istack_pointer_valid(*stack, sizeof(*stack)))
        return STACK_OP_PTRINVALID;
    
    
    StackRigidState integrityChecks = StackValidate(*stack);
    
    if (integrityChecks != STACK_ST_OK) {
        StackDumpWrapperWhy(*stack, "StackPush operation spotted integrity error");
        return STACK_OP_INTEGRITYERR;
    }
    
    
    StackRigidOperationCodes reallocResult = __StackReallocate(stack, 1);
    
    if (reallocResult != STACK_OP_OK) {
        StackDumpWrapperWhy(*stack, "StackPop operation spotted integrity error during the reallocation");
        return reallocResult;
    }
    
    (*stack)->data[(*stack)->size] = value;
    (*stack)->size += 1;
    
    __StackUpdateChecksum(*stack);
    
    if ((*stack)->size == 0) {
        return STACK_OP_OVERFLOW;
    }
    return STACK_OP_OK;
}
References __StackReallocate(), __StackUpdateChecksum(), STACK_OP_INTEGRITYERR, STACK_OP_OK, STACK_OP_OVERFLOW, STACK_OP_PTRINVALID, STACK_ST_OK, StackDumpWrapperWhy, and StackValidate().
Referenced by main().
size_t StackRigidMemoryUse (__overload(StackRigid) * stack)
Memory alocated for the Stack.
Parameters
stack Stack to be checked
Returns
alocated bytes
                                                           {
    assert(stack);
    return sizeof(__overload(StackRigid)) + (stack->capacity - 1) * sizeof(StackElementType);
}
References __overload, and StackElementType.
Referenced by __StackGetChecksum(), __StackReallocate(), main(), StackDestruct(), and StackDump().
StackRigidState StackValidate (__overload(StackRigid) * stack)
Perform all stack checks: checksums, general constrains.
Parameters
stack Stack to be validated
Returns
calculated state
                                                              {
    if (!istack_pointer_valid(stack, sizeof(stack)))
        return STACK_ST_NULL;
    
    if (stack->size > stack->capacity || stack->checkSum == 0 || stack->checkSumVital == 0)
        return STACK_ST_INTEGRITYERR;
    
    #ifndef IGNORE_VALIDITY
        uint32_t currentChecksumVital = __StackGetChecksumVital(stack);
        if (currentChecksumVital != stack->checkSumVital || currentChecksumVital == 0)
            return STACK_ST_INTEGRITYERR;
        
        uint32_t currentChecksum = __StackGetChecksum(stack);
        if (currentChecksum != stack->checkSum || currentChecksum == 0)
            return STACK_ST_INTEGRITYERR;
    #endif
    return STACK_ST_OK;
}
References __StackGetChecksum(), __StackGetChecksumVital(), STACK_ST_INTEGRITYERR, STACK_ST_NULL, and STACK_ST_OK.
Referenced by main(), StackBack(), StackDestruct(), StackDump(), StackPop(), and StackPush().
Variable Documentation
size_t added = memory + (capacity - 1) * sizeof(StackElementType)
pointer capacity = capacity
pointer checkSum = 0
pointer checkSumVital = 0
pointer logFile
Initial value:
{
     if (capacity == 0)
         capacity = 1
memory = sizeof( __overload(StackRigid))
Referenced by __StackGetChecksum(), __StackGetChecksumVital(), __StackReallocate(), and StackDump().
return pointer
pointer size = 0
Author
Generated automatically by Doxygen for StackRigid from the source code.